Moved Message sending to Message Manager as per issue #28
lotgd/core pull request #114
Opened 2018-04-07 19:17 UTC by nekosune

Sorry it took so long, I actually have more time now -_-

2018-04-09 08:20 UTC, Vassyli requested changes
Good work, thank you!
I've annotated a few things that should be changed before we merge.
Also, please try to add a few tests so that you (and we) can be sure everything works as intended.

2018-04-09 08:20 UTC, Vassyli commented on src/Models/Message.php
> +     * Use the static methods self::send() and self::sendSystemMessage() instead.
These methods don't exist anymore. You can remove this message or hint the usage of MessageManager.

2018-04-09 08:20 UTC, Vassyli commented on src/GameBuilder.php
> +    public function useMessageManager(string $messageManagerFqcn): self
Since we are introducing a new Manager, I'd prefer to use the withMessageManager-Syntax (the message manager of choice can then be supplied via bootstrap)

2018-04-09 08:20 UTC, Vassyli commented on src/MessageManager.php
> + */
Please consider removing it (you are automatically attributed as the author via the git system anyway). If you insist, use DocType-Syntax instead (`@author`) and remove date/time.

2018-04-09 08:20 UTC, Vassyli commented on src/MessageManager.php
> +        $message=new Message($from, $message, $thread, $systemMessage);
We prefer spaces around any operator, except object operators.

2018-04-09 08:20 UTC, Vassyli commented on src/MessageManager.php
> +        $message=new Message(SystemCharacter::getInstance(), $message, $thread, true);
We prefer spaces around any operator, except object operators.

2018-04-09 08:20 UTC, Vassyli commented on src/Game.php
> +    public function setMessageManager(MessageManager $messageManager) : void
No space between the closing bracket and the colon: `$messageManager): void`

2018-04-09 08:20 UTC, Vassyli commented on src/Game.php
> +        $this->messageManager=$messageManager;
No space around `=`

2018-04-09 08:20 UTC, Vassyli commented on src/GameBuilder.php
>      private $diceBagClass;
Between any block, we prefer an empty line.

2018-04-09 08:20 UTC, Vassyli commented on src/MessageManager.php
> +
Only 1 empty line between blocks.

2018-04-09 08:20 UTC, Vassyli commented on src/MessageManager.php
> + */
Additionally, you are missing a use_strict declaration.

2018-04-09 16:04 UTC, nekosune commented
Made the requested changes!

2018-04-12 09:27 UTC, Vassyli approved these changes
I'll push this into master. Thank you for the work!

2018-04-12 09:48 UTC, merged